#version: '3.8'
#
#services:
#  app:
#    build: .
#    container_name: myapp
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      DB_URL: jdbc:postgresql://app-network:5432/library_db
#      DB_USER: library_app
#      DB_PASSWORD: 1395
#      DB_DRIVER: org.postgresql.Driver
#      DB_POOL_SIZE: 10
#      DB_POOL_MIN_IDLE: 2
#    volumes:
#      - ./.m2:/root/.m2
#    #    networks:
#    #      - app-network
#    links:
#      - "db:app-network"
#
#  db:
#    image: postgres:17
#    container_name: postgres_db
#    environment:
#      POSTGRES_DB: library_db
#      POSTGRES_USER: library_app
#      POSTGRES_PASSWORD: 1395
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
##    networks:
##      - app-network
#
#volumes:
#  postgres_data:
#
##networks:
##  app-network:
##    driver: bridge

version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local